name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4

      - name: Disable root warning
        run: sed -i 's/^warn_on_root.*/warn_on_root = 0/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
